[package]
name = "boreal"
version = "1.0.1"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = { version = "0.8.9", features = ["multipart"] }
dirs = "6.0.0"
libc = "0.2.189"
log = "0.4.34"
reqwest = { version = "0.13.2", default-features = false, features = ["blocking", "json", "rustls"] }
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal", "pollster"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
webbrowser = "1.2.4"
zip = "8.6.0"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
ksni = "0.3.6"

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
tao = { version = "0.35.0", default-features = false }
tray-icon = { version = "0.24.2", default-features = false }

[build-dependencies]
winresource = "0.1.23"
