pub mod command;
pub mod config;
pub mod gui;
pub mod install;
pub mod remotes;

use std::{
    error::Error,
    path::PathBuf,
};

use crate::bootstrap::Runtime;

pub type RcloneError =
    Box<dyn Error + Send + Sync>;

/// Current state of the BOREAL-managed Rclone executable.
#[derive(Debug, Clone)]
pub struct RcloneStatus {
    /// Full path to the BOREAL-managed Rclone executable.
    pub path: PathBuf,

    /// Version string reported by `rclone version`.
    pub version: String,

    /// Authenticated URL generated by `rclone gui`.
    pub gui_url: Option<String>,
}

/// Return the expected BOREAL-managed Rclone executable path.
pub fn executable_path(
    runtime: &Runtime,
) -> Result<PathBuf, RcloneError> {
    let bin_dir = runtime
        .directories
        .get("BIN")
        .ok_or(
            "BOREAL BIN directory is not configured",
        )?;

    let executable_name = if cfg!(windows) {
        "rclone.exe"
    } else {
        "rclone"
    };

    Ok(
        bin_dir.join(
            executable_name,
        ),
    )
}

/// Detect the BOREAL-managed Rclone installation.
///
/// This does not search PATH because BOREAL intentionally
/// manages and uses its own private Rclone executable.
pub fn detect(
    runtime: &Runtime,
) -> Result<Option<RcloneStatus>, RcloneError> {
    let path = executable_path(
        runtime,
    )?;

    if !path.is_file() {
        return Ok(
            None,
        );
    }

    let version = command::version(
        &path,
    )?;

    Ok(
        Some(
            RcloneStatus {
                path,
                version,
                gui_url: None,
            },
        ),
    )
}

/// Ensure that BOREAL has a working Rclone executable.
///
/// If Rclone is missing, BOREAL automatically installs
/// a private user-local copy.
///
/// If an existing managed executable is unusable,
/// BOREAL attempts to replace it.
pub fn ensure_installed(
    runtime: &Runtime,
) -> Result<RcloneStatus, RcloneError> {
    match detect(
        runtime,
    ) {
        Ok(
            Some(
                status,
            ),
        ) => {
            if supports_embedded_gui(
                &status.version,
            ) {
                return Ok(
                    status,
                );
            }

            println!(
                "BOREAL-managed {} predates the embedded Rclone GUI.",
                status.version
            );

            println!(
                "BOREAL will update Rclone."
            );
        }

        Ok(
            None,
        ) => {
            println!(
                "BOREAL-managed Rclone was not found."
            );
        }

        Err(
            error,
        ) => {
            eprintln!(
                "Existing BOREAL Rclone installation is not usable: {error}"
            );

            eprintln!(
                "BOREAL will reinstall Rclone."
            );
        }
    }

    let installed_path = install::install(
        runtime,
    )?;

    let version = command::version(
        &installed_path,
    )?;

    Ok(
        RcloneStatus {
            path: installed_path,
            version,
            gui_url: None,
        },
    )
}

/// The dedicated `rclone gui` command with its embedded UI was
/// introduced in Rclone v1.74.
fn supports_embedded_gui(
    version: &str,
) -> bool {
    let Some(
        version,
    ) = version.strip_prefix(
        "rclone v",
    ) else {
        return false;
    };

    let mut parts = version.split(
        '.',
    );

    let major = parts
        .next()
        .and_then(
            |part| part.parse::<u32>().ok(),
        );

    let minor = parts
        .next()
        .and_then(
            |part| part.parse::<u32>().ok(),
        );

    matches!(
        (major, minor),
        (Some(major), Some(minor))
            if major > 1 || (major == 1 && minor >= 74)
    )
}
